export const NAV = [
  ["Dashboard", "/dashboard"],
  ["Farm Financials", "/farm-financials"],
  ["Plan", "/plan"],
  ["Reports", "/reports"],
  ["Farm Data", "/farm-data"],
  ["Documents", "/documents"],
  ["Notifications", "/notifications"],
  ["Events", "/events"],
  ["Tasks", "/tasks"],
  ["Invoices", "/invoices"],
  ["Schemes", "/schemes"],
  ["Processors", "/processors"],
  ["Suppliers", "/suppliers"],
  ["Farm Actions", "/farm-actions"],
];
